name: Create Pack
on:
  push:
    branches-ignore:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2

    - name: Create Pack
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH }}
        script: |
          cd "./packs/Classic-Faithful-64x-Jappa/${{ steps.branch-name.outputs.current_branch }}"
          git pull
          zip -r "Classic Faithful 64x Jappa - ${{ steps.branch-name.outputs.current_branch }}.zip" . -x "*.git*" -x "*.github*" -x ".gitignore"
          mv "Classic Faithful 64x Jappa - ${{ steps.branch-name.outputs.current_branch }}.zip" "/var/www/html/database.faithfulpack.net/packs/Classic-64x-Java/Jappa"